services:
  - type: web
    name: geoaino-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
    runtime: python
    region: frankfurt
    plan: free
    branch: main
    repo: https://github.com/ton-utilisateur/geo-aino-supreme
    buildFilter:
      paths: ["backend/**", "requirements.txt"]
    envVars:
      - key: OPENAI_API_KEY
        value: sk-xxxxxxx

  - type: static
    name: geoaino-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: frontend/dist
    buildFilter:
      paths: ["frontend/**"]
