services:
  - type: web
    name: aino-backend
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npm install --prefix frontend
      npm run build --prefix frontend
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    env: python
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
